CREATE OR REPLACE FUNCTION CalculateAge(
  DOB IN DATE
)
RETURN NUMBER
IS 
  AGE NUMBER;
BEGIN
  AGE := FLOOR(MONTHS_BETWEEN(SYSDATE, DOB) / 12);
  RETURN AGE;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE(CalculateAge(TO_DATE('1975-05-15', 'YYYY-MM-DD')));
END;
/